let result = try {
    1 + 1
} catch {
    assert(false)
}

assertEqual(result, 2)

let result2 = try {
    list::column(1, 1)
    assert(false)
} catch e: String {
    assert(false)
} catch e {
    assert(isType(e, String))

    "caught"
}

assertEqual(result2, "caught")

struct CustomError(msg)
let result3 = try {
    throw new CustomError(123)
    assert(false)
} catch e: CustomError {
    e->msg
} catch {
    assert(false)
}

assertEqual(result3, 123)